apiVersion: apps/v1
kind: Deployment

metadata:
  name: payroll-service

spec:
  replicas: 2

  selector:
    matchLabels:
      app: payroll-service

  template:
    metadata:
      labels:
        app: payroll-service

    spec:
      containers:
      - name: payroll-service

        image: 123456789012.dkr.ecr.ap-south-1.amazonaws.com/payroll-service:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"

          limits:
            memory: "1Gi"
            cpu: "500m"