---
- name: Create Vault configuration directory
  ansible.builtin.file:
    path: /etc/vault.d
    state: directory
    mode: "0750"

- name: Copy Vault configuration
  ansible.builtin.copy:
    src: ../../../../../security/vault/config/vault.hcl
    dest: /etc/vault.d/vault.hcl
    mode: "0640"

- name: Run Vault
  community.docker.docker_container:
    name: vault
    image: hashicorp/vault:1.17
    restart_policy: unless-stopped
    capabilities:
      - IPC_LOCK
    published_ports:
      - "8200:8200"
    command: server -config=/vault/config/vault.hcl
    volumes:
      - /etc/vault.d:/vault/config:ro
      - vault-data:/vault/file
