pipeline {

```
agent any

environment {
    IMAGE_NAME = "notification-service"
}

stages {

    stage('Checkout') {
        steps {
            git branch: 'main',
            url: 'https://github.com/HariPolavarapu/hari-enterprise-devops-platform.git'
        }
    }

    stage('Install Dependencies') {
        steps {
            sh 'pip install -r requirements.txt'
        }
    }

    stage('Code Validation') {
        steps {
            sh 'python -m py_compile app/main.py'
        }
    }

    stage('Security Scan') {
        steps {
            echo 'Running Trivy security scan'
        }
    }

    stage('Docker Build') {
        steps {
            sh 'docker build -t $IMAGE_NAME .'
        }
    }

    stage('Push To AWS ECR') {
        steps {
            echo 'Pushing Docker image to AWS ECR'
        }
    }

    stage('GitOps Deployment') {
        steps {
            echo 'Triggering ArgoCD deployment'
        }
    }
}

post {

    success {
        echo 'Notification Service Pipeline Completed Successfully'
    }

    failure {
        echo 'Pipeline Failed'
    }
}
```

}
