sonar.projectKey=enterprise-devops-platform
sonar.projectName=Enterprise DevOps Platform
sonar.sources=applications
sonar.tests=applications
sonar.test.inclusions=**/tests/**,**/src/test/**
sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/bin/**,**/obj/**
sonar.java.binaries=applications/employee-java-service/target/classes
sonar.coverage.jacoco.xmlReportPaths=applications/employee-java-service/target/site/jacoco/jacoco.xml
