---
- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose-v2
    state: present
    update_cache: true

- name: Enable Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
