apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: platform-reader
  namespace: enterprise-platform
rules:
  - apiGroups: ["", "apps", "batch"]
    resources: ["pods", "pods/log", "services", "configmaps", "deployments", "jobs"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: platform-reader
  namespace: enterprise-platform
subjects:
  - kind: Group
    name: platform-readers
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: platform-reader
  apiGroup: rbac.authorization.k8s.io
