pipeline {

    agent any

    environment {
        IMAGE_NAME = "payroll-service"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                url: 'https://github.com/HariPolavarapu/hari-enterprise-devops-platform.git'
            }
        }

        stage('Restore Dependencies') {
            steps {
                sh 'dotnet restore'
            }
        }

        stage('Build') {
            steps {
                sh 'dotnet build --configuration Release'
            }
        }

        stage('Test') {
            steps {
                sh 'dotnet test'
            }
        }

        stage('Security Scan') {
            steps {
                echo 'Running Trivy Scan'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Push To AWS ECR') {
            steps {
                echo 'Pushing image to AWS ECR'
            }
        }

        stage('GitOps Deployment') {
            steps {
                echo 'Triggering ArgoCD deployment'
            }
        }
    }

    post {

        success {
            echo 'Payroll Pipeline Success'
        }

        failure {
            echo 'Payroll Pipeline Failed'
        }
    }
}